# permissions for end users to edit orchestrationdemoapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orchestrationdemoapi-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orchestration-demo-operator
    app.kubernetes.io/part-of: orchestration-demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationdemoapi-editor-role
rules:
- apiGroups:
  - ashokgudise.demos.com
  resources:
  - orchestrationdemoapis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ashokgudise.demos.com
  resources:
  - orchestrationdemoapis/status
  verbs:
  - get
