# permissions for end users to view orchestrationdemoapis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: orchestrationdemoapi-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: orchestration-demo-operator
    app.kubernetes.io/part-of: orchestration-demo-operator
    app.kubernetes.io/managed-by: kustomize
  name: orchestrationdemoapi-viewer-role
rules:
- apiGroups:
  - ashokgudise.demos.com
  resources:
  - orchestrationdemoapis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ashokgudise.demos.com
  resources:
  - orchestrationdemoapis/status
  verbs:
  - get
